name: Rust CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        build_type: [debug, release]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          submodules: recursive

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.build_type }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      # Run tests
      - name: Test
        shell: bash
        run: |
          if [ "${{ matrix.build_type }}" == "release" ]; then
            cargo test --release
          else
            cargo test
          fi

      # Build the project
      - name: Build
        shell: bash
        run: |
          if [ "${{ matrix.build_type }}" == "release" ]; then
            cargo build --release
          else
            cargo build
          fi

      # Upload artifacts if build succeeds
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UnchainedPlugin-${{matrix.build_type}}
          path: |
            target/${{ matrix.build_type }}/UnchainedPlugin.dll
          if-no-files-found: warn