name: C++ CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          submodules: recursive

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.build_type }}

      - uses: lukka/get-cmake@latest
      
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      # Ensure build directory exists
      - name: Create build directory
        run: mkdir -p ${{github.workspace}}/build

      # Use the latest Visual Studio toolset in CMake
      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -T v143 -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      # Build the project
      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      # Upload artifacts if build succeeds
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UnchainedPlugin-${{matrix.build_type}}
          path: ${{github.workspace}}/build/Output/*
          if-no-files-found: warn  # Don't fail if no files are found